### ISSUE TITLE
Improving the UI

### ISSUE THREAD

**Issue by cnohall** [dj0wns/AoE_Openings#2]
Hello, 

I'm itching to help improve the UI for this website. Wonder if you're willing to review some upcoming PR aimed at improving the UI?

**Comment by dj0wns** [comment]
What did you have in mind?

**Comment by cnohall** [comment]
Mostly small changes, such as adjusting the margins somewhat. I'll create a PR and leave it up to you if you want to use it or not.

**Comment by dj0wns** [comment]
That would be greatly appreciated. As a primarily back end dev I don't really have an eye for that. Looking forward to see what you do!

**Comment by cnohall** [comment]
Thanks!
