### ISSUE TITLE
No permissions to push a branch.

### ISSUE THREAD

**Issue by cnohall** [dj0wns/AoE_Openings#3]
Hi,

When I try to push changes to a separate branch it keeps denying me.

![image](https://user-images.githubusercontent.com/36883813/193377773-eae84f48-3f89-4014-8c2e-b63b1c23ee16.png)

Would it be possible to add me as a collaborator, with the lowest possible rights? If you don't like my suggested changes you can always remove me as a collaborator.

**Comment by dj0wns** [comment]
Send a pull request from your fork

**Comment by cnohall** [comment]
Thanks, will do!
